### PR TITLE
Fix issue #83 and implement peer description comming from openbgpd

### LINKED ISSUE #83: Erroneous peer description on OpenBGP peers.
When using openbgp and bgp-state-server, the peer description is set to the format `PEER AS{ASN} {PEER_ADDRESS}` instead of the given description from bgp-state-server.

(PR is coming to fix this)

### PR DESCRIPTION
**Pull request by mrevilme**
Before
Screenshot 2021-11-15 at 10 28 14
After:
Screenshot 2021-11-15 at 10 25 45

Closes #83

### CODE REVIEW

**Comment by annikahannig** [comment]
Awesome! :)
Thank you!

File: pkg/sources/openbgpd/decoders.go [hunk 1]
```diff
@@ -57,9 +57,14 @@ func decodeNeighbor(n interface{}) (*api.Neighbour, error) {
 
 // describeNeighbor creates a neighbor description
 func describeNeighbor(nb interface{}) string {
-	addr := decoders.MapGetString(nb, "remote_addr", "invalid_address")
-	asn := decoders.MapGetString(nb, "remote_as", "")
-	return fmt.Sprintf("PEER AS%s %s", asn, addr)
+	desc := decoders.MapGetString(nb, "description", "")
+	if desc != "" {
+		return desc
+	} else {
```
Comment (annikahannig) [inline pkg/sources/openbgpd/decoders.go:63]: technically this else is not required :)

**Review by annikahannig — APPROVED** [review]
